name: Notif
env: 
  SLACK_API_TOKEN: ${{ secrets.SLACK_API_TOKEN }}
  TEST: ${{ secrets.TEST }}

on:
  schedule:
    - cron: "0 4 * * *"
  workflow_dispatch:

jobs:
  notif: 
    runs-on: ubuntu-latest

    steps:
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install requirements
      run: python -m pip install slackclient slack pandas
    - uses: actions/checkout@v2
    - name: notify
      env: 
        SLACK_API_TOKEN: ${{ secrets.SLACK_API_TOKEN }}
        TEST: ${{ secrets.TEST }}
      run: python bot.py