name: test
env: 
  TEST: ${{ secrets.TEST }}


# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  schedule:
    - cron: "0 4 * * *"
  workflow_dispatch:

jobs:
  greeting_job:
    runs-on: ubuntu-latest
    env:
     TEST: ${{ secrets.TEST }}
    steps:
      - name: "test"
        run: echo TEST
        env:
          TEST: ${{ secrets.TEST }}
